/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author akshat
 */
public class displayimage extends javax.swing.JFrame {
        
    JScrollPane jsp;
    JLabel label = new JLabel();
    
    /**
     * Creates new form displayimage
     */
    public displayimage() {
        initComponents();
    }
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    public void addImage()
    {
        int i=1;
        JPanel jpl1=new JPanel();
        label.setBounds(10,10,276,193);
        jsp=new JScrollPane(jpl1);
        jpl1.setLayout(new FlowLayout());
        
        
         while(i<=12)
            {
                String filename="C:\\Users\\akshat\\OneDrive\\Desktop\\Mini Project\\final dataset\\Image"+i+".jpg";
                System.out.println(filename);
                ImageIcon image=new ImageIcon(filename);
                
                
                JLabel l=new JLabel();
                l.setIcon(image);
                
                
                jpl1.add(l);
                i=i+1;
                
                
            }
         jpl1.setBounds(50,50,500,250);
         
         getContentPane().add(jpl1);
         setVisible(true);
         
    }
    
    
    //final JLabel imageLabel = new JLabel(new ImageIcon(image));
    //final JScrollPane scroll = new JScrollPane(imageLabel);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        new displayimage().addImage();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
